# wrangler.toml
name = "spam-detector-bot"
main = "src/index.js"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[vars]
# 这些变量需要在部署时设置
# TELEGRAM_BOT_TOKEN = "your_telegram_bot_token"
# ADMIN_CHAT_ID = "your_admin_chat_id"
# MANAGED_CHAT_ID = "your_managed_chat_id"
# AI_API_KEY = "your_ai_api_key"

# KV 命名空间配置
[[kv_namespaces]]
binding = "KV"
# id = "your_kv_namespace_id"
